name: "Write PR comment with validation results"

on:
    workflow_run:
        workflows: ["Validate new plugin"]
        types: [completed]  # Runs regardless of completion status; status can be checked from the event context.

jobs:
    write-pr-comment-with-validation-results:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        env:
            GH_TOKEN: ${{ secrets.PLUGIN_PR_WORKFLOW }}
            GH_REPO: ${{ github.repository }}
        steps:
            - name: Fetch file
              uses: actions/download-artifact@v8
              with:
                  path: pr-data
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ github.event.workflow_run.id }}

            - name: Print file contents
              run: |
                  set -ex
                  find .
                  PR_NUM=$(cat pr-data/pr-num.txt)
                  PR_AUTHOR=$(cat pr-data/pr-author.txt)
                  VALIDATION_RESULTS=pr-data/validation-results.md

                  # Append the PR author to the file.
                  # Using printf for compatibility; part of posix standard
                  # where echo is not.
                  # NOTE: the literal `@` is needed here since this is in the
                  # body of the comment.
                  printf "\n\nFYI @${PR_AUTHOR}\n" >> "$VALIDATION_RESULTS"

                  # debugging
                  cat "$VALIDATION_RESULTS"

                  # Write the validation results to the PR
                  gh pr comment \
                        "$PR_NUM" \
                        --body-file "$VALIDATION_RESULTS" \
                        --repo "$GH_REPO"

                  VALIDATION_STATUS=$(cat pr-data/validation-status.txt)
                  REVIEWER_POOL="natcap/plugin-reviewers"
                  if [[ "$VALIDATION_STATUS" = "passed" ]]
                  then
                      gh pr edit \
                        "$PR_NUM" \
                        --repo "$GH_REPO" \
                        --add-reviewer "$REVIEWER_POOL"
                  fi

                  # If the review rubric hasn't already been commented, add it
                  API_ENDPOINT=/repos/"$GH_REPO"/issues/"$PR_NUM"/comments
                  SEARCH_STRING="## Dear Reviewer,"

                  if
                      [[ "$VALIDATION_STATUS" = "passed" ]] &&
                      ! gh api --paginate --slurp "$API_ENDPOINT" | grep -q "$SEARCH_STRING"
                  then
                      gh pr comment "$PR_NUM" --body-file="review-rubric.md"
                  fi
