name: "Validate new plugin"

on:
    pull_request:
        types: [opened, reopened]
        paths:
            - 'plugins.json'
    push:
        paths:
            - 'plugins.json'
            - '.github/workflows/plugin-pr-validate.yml'
            - 'scripts/lint-metadata.py'
            - 'scripts/extract-modified-json.py'
            - 'scripts/validateall.sh'

permissions:
    contents: read
    pull-requests: write

jobs:
    plugin-validation-pr:
        runs-on: ubuntu-latest
        env:
            PR_NUMBER: ${{ github.event.number }}
            REPO: ${{ github.repository }}
            GH_TOKEN: ${{ github.token }}
            TARGET_FILE: "validation-results.md"
        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-python@v6
              with:
                  python-version: "3.14"
                  cache: "pip"
                  python-version-file: ".python-version"

            - name: Install uv
              uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

            - name: Extract the new plugin data and lint it
              shell: bash
              id: validate
              run: |
                  set -ex  # fail script on first command failure.

                  scripts/validateall.sh "$TARGET_FILE"

            - name: Record additional context for later comment
              shell: bash
              if: always()
              run: |
                  mkdir pr-data
                  echo "$PR_NUMBER" > pr-data/pr-num.txt
                  echo ${{ github.event.pull_request.user.login }} > pr-data/pr-author.txt
                  cp "$TARGET_FILE" pr-data/

                  # Validation failure can be noted by nonzero exit status
                  # (first part of script) or by the red x emoji in the output
                  # file.  Handle both cases.
                  VALIDATION_EXITED_NONZERO=${{ steps.validate.outcome }}
                  if (grep ❌ "$TARGET_FILE" ||
                        [[ "$VALIDATION_EXITED_NONZERO" = "failure" ]])
                  then
                      printf "failed" > pr-data/validation-status.txt
                      exit 1  # fail the action!  The downstream actions should still run.
                  else
                      printf "passed" > pr-data/validation-status.txt
                  fi

            - name: Upload artifact
              if: always()
              uses: actions/upload-artifact@v7
              with:
                  path: pr-data
